# Generated by Django 3.0.4 on 2020-03-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_date',
            field=models.DateField(),
        ),
    ]
