# Generated by Django 3.0.4 on 2020-03-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20200329_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='modified',
            field=models.BooleanField(default=True),
        ),
    ]
