# Generated by Django 3.0.4 on 2020-03-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20200329_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='input_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='modified_date',
            field=models.DateTimeField(),
        ),
    ]
