# Generated by Django 3.0.4 on 2020-03-29 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0008_auto_20200329_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateField(auto_now_add=True)),
                ('category_name', models.CharField(max_length=30)),
                ('google_form_link', models.CharField(max_length=800)),
                ('category_secrate_key', models.CharField(max_length=100)),
                ('category_description', models.TextField(default='Please answer all the questions in this category')),
                ('category_status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
