# Generated by Django 3.0.4 on 2020-03-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='google_form_link',
            field=models.TextField(default='null'),
        ),
    ]
