# Generated by Django 3.0.4 on 2020-03-30 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gforms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='head',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_desable_user',
            field=models.BooleanField(default=False, verbose_name='suspendes School Admin '),
        ),
        migrations.CreateModel(
            name='schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateField(auto_now_add=True)),
                ('school_name', models.CharField(max_length=100)),
                ('school_mail', models.EmailField(max_length=256)),
                ('school_phone_number', models.PositiveIntegerField()),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('school_website_link', models.CharField(max_length=300)),
                ('school_status', models.BooleanField(default=False)),
                ('school_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
