# Generated by Django 3.0.4 on 2020-03-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gforms', '0002_auto_20200330_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='schools',
            new_name='school',
        ),
    ]
